# Generated by Django 5.0.1 on 2024-02-13 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Scheme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('pomodoro', models.TextField(max_length=20)),
                ('short_break', models.TextField(max_length=20)),
                ('long_break', models.TextField(max_length=20)),
                ('long_break_delay', models.TextField(max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
