# Generated by Django 5.0.1 on 2024-02-13 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pomodoro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField(auto_now_add=True)),
                ('end_time', models.DateTimeField(auto_now=True)),
                ('duration', models.DurationField()),
                ('is_break', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['-end_time'],
            },
        ),
    ]
