# Generated by Django 5.0.1 on 2024-03-08 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pomodoro', '0003_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pomodoro',
            options={'ordering': ['-user']},
        ),
        migrations.RenameField(
            model_name='pomodoro',
            old_name='start_time',
            new_name='created_at',
        ),
        migrations.RemoveField(
            model_name='pomodoro',
            name='duration',
        ),
        migrations.RemoveField(
            model_name='pomodoro',
            name='end_time',
        ),
        migrations.AddField(
            model_name='pomodoro',
            name='auto_start_break',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='pomodoro',
            name='auto_start_pomodoro',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='pomodoro',
            name='daily_goal',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='pomodoro',
            name='is_long_break',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='pomodoro',
            name='is_pomodoro',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='pomodoro',
            name='long_break_delay',
            field=models.IntegerField(default=4),
        ),
        migrations.AddField(
            model_name='pomodoro',
            name='long_break_duration',
            field=models.IntegerField(default=15),
        ),
        migrations.AddField(
            model_name='pomodoro',
            name='pomodoro_count',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='pomodoro',
            name='pomodoro_duration',
            field=models.IntegerField(default=25),
        ),
        migrations.AddField(
            model_name='pomodoro',
            name='short_break_duration',
            field=models.IntegerField(default=5),
        ),
    ]
