# Generated by Django 5.0.1 on 2024-03-08 15:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pomodoro', '0004_alter_pomodoro_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pomodoro',
            options={'ordering': ['-created_at']},
        ),
    ]
