# Generated by Django 5.0.1 on 2024-03-09 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pomodoro', '0005_alter_pomodoro_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='pomodoro',
            name='settings_name',
            field=models.CharField(default='classic', max_length=50),
        ),
    ]
