# Generated by Django 5.0.1 on 2024-03-15 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pomodoro', '0007_alter_pomodoro_long_break_duration_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pomodoro',
            name='pomodoro_count',
            field=models.IntegerField(default=0),
        ),
    ]
