# Generated by Django 5.0.1 on 2024-03-21 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pomodoro', '0010_pomodoro_current_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='pomodoro',
            name='is_disabled',
            field=models.BooleanField(default=True),
        ),
    ]
