# Generated by Django 5.0.1 on 2024-03-26 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pomodoro', '0011_pomodoro_is_disabled'),
    ]

    operations = [
        migrations.AddField(
            model_name='pomodoro',
            name='alarm_sound',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='pomodoro',
            name='one_min_notify',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='pomodoro',
            name='ticking_sound',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='pomodoro',
            name='ticking_sound_break',
            field=models.BooleanField(default=False),
        ),
    ]
