# Generated by Django 5.0.1 on 2024-04-01 23:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0003_task_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='assigned_pomodoros',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='task',
            name='remaining_pomodoros',
            field=models.IntegerField(default=1),
        ),
    ]
